import type { Ticket } from './types';

// Mock ticket data for practice (no backend / no database).
// Covers a mix of status / priority / category so filtering, search, and
// stats can be exercised. Note: in-app "edits" only mutate in-memory state;
// a page refresh resets everything back to this data.

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-1001',
    title: 'Cannot log in to company email',
    requesterName: 'Alice Chen',
    requesterEmail: 'alice.chen@example.com',
    category: 'email',
    priority: 'high',
    status: 'open',
    description:
      'Since this morning Outlook keeps saying my password is wrong, and webmail will not let me in either, but I am sure I did not change it. Please help as soon as possible.',
    createdAt: '2026-06-16T01:12:00.000Z',
    updatedAt: '2026-06-16T01:12:00.000Z',
    activities: [
      {
        id: 'ACT-1001-1',
        type: 'created',
        author: 'Alice Chen',
        content: 'Ticket created.',
        createdAt: '2026-06-16T01:12:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1002',
    title: 'Conference room Wi-Fi keeps dropping',
    requesterName: 'Bob Martinez',
    requesterEmail: 'bob.martinez@example.com',
    category: 'network',
    priority: 'medium',
    status: 'in_progress',
    description:
      'The Wi-Fi in the east-side conference room on the 3rd floor drops every few minutes and constantly interrupts video calls. Other floors are fine.',
    createdAt: '2026-06-15T07:40:00.000Z',
    updatedAt: '2026-06-16T02:05:00.000Z',
    assignedTo: 'IT - Daniel',
    activities: [
      {
        id: 'ACT-1002-1',
        type: 'created',
        author: 'Bob Martinez',
        content: 'Ticket created.',
        createdAt: '2026-06-15T07:40:00.000Z',
      },
      {
        id: 'ACT-1002-2',
        type: 'status_changed',
        author: 'IT - Daniel',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-15T08:15:00.000Z',
      },
      {
        id: 'ACT-1002-3',
        type: 'note',
        author: 'IT - Daniel',
        content:
          'Contacted the network vendor. Initial guess is AP overload in that area; scheduling an on-site check.',
        createdAt: '2026-06-16T02:05:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1003',
    title: 'Request to install Adobe Photoshop',
    requesterName: 'Carol Wang',
    requesterEmail: 'carol.wang@example.com',
    category: 'software',
    priority: 'low',
    status: 'waiting',
    description:
      'Marketing needs Photoshop to work on event assets. Requesting installation on my work computer and a license assignment.',
    createdAt: '2026-06-14T03:20:00.000Z',
    updatedAt: '2026-06-15T06:30:00.000Z',
    assignedTo: 'IT - Emma',
    activities: [
      {
        id: 'ACT-1003-1',
        type: 'created',
        author: 'Carol Wang',
        content: 'Ticket created.',
        createdAt: '2026-06-14T03:20:00.000Z',
      },
      {
        id: 'ACT-1003-2',
        type: 'reply',
        author: 'IT - Emma',
        content:
          'This needs the department manager to approve the license budget. Sent a confirmation email and waiting for a reply.',
        createdAt: '2026-06-15T06:30:00.000Z',
      },
      {
        id: 'ACT-1003-3',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from Open to Waiting.',
        createdAt: '2026-06-15T06:30:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1004',
    title: 'Laptop will not power on',
    requesterName: 'David Kim',
    requesterEmail: 'david.kim@example.com',
    category: 'hardware',
    priority: 'urgent',
    status: 'in_progress',
    description:
      'Pressing the power button does nothing, no indicator light, and I have already swapped the charger. I have a client demo tomorrow and need this fixed urgently.',
    createdAt: '2026-06-16T00:05:00.000Z',
    updatedAt: '2026-06-16T03:10:00.000Z',
    assignedTo: 'IT - Daniel',
    activities: [
      {
        id: 'ACT-1004-1',
        type: 'created',
        author: 'David Kim',
        content: 'Ticket created.',
        createdAt: '2026-06-16T00:05:00.000Z',
      },
      {
        id: 'ACT-1004-2',
        type: 'status_changed',
        author: 'IT - Daniel',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-16T00:30:00.000Z',
      },
      {
        id: 'ACT-1004-3',
        type: 'note',
        author: 'IT - Daniel',
        content:
          'Prepared a loaner laptop and migrating data; also contacting the vendor to test the mainboard.',
        createdAt: '2026-06-16T03:10:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1005',
    title: 'Need GitHub organization access',
    requesterName: 'Eva Liu',
    requesterEmail: 'eva.liu@example.com',
    category: 'access',
    priority: 'medium',
    status: 'resolved',
    description:
      'New engineer onboarding. I need to join the company GitHub organization and get write access to the backend repository.',
    createdAt: '2026-06-12T02:00:00.000Z',
    updatedAt: '2026-06-13T01:25:00.000Z',
    assignedTo: 'IT - Emma',
    activities: [
      {
        id: 'ACT-1005-1',
        type: 'created',
        author: 'Eva Liu',
        content: 'Ticket created.',
        createdAt: '2026-06-12T02:00:00.000Z',
      },
      {
        id: 'ACT-1005-1b',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-12T06:00:00.000Z',
      },
      {
        id: 'ACT-1005-2',
        type: 'reply',
        author: 'IT - Emma',
        content:
          'Sent the org invite and added you to the backend team with write access. Please check your email and accept the invite.',
        createdAt: '2026-06-13T01:20:00.000Z',
      },
      {
        id: 'ACT-1005-3',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from In Progress to Resolved.',
        createdAt: '2026-06-13T01:25:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1006',
    title: 'VPN connection times out',
    requesterName: 'Frank Zhou',
    requesterEmail: 'frank.zhou@example.com',
    category: 'network',
    priority: 'high',
    status: 'open',
    description:
      'Working remotely from home. Connecting to the company VPN keeps timing out, which blocks access to internal systems.',
    createdAt: '2026-06-15T22:48:00.000Z',
    updatedAt: '2026-06-15T22:48:00.000Z',
    activities: [
      {
        id: 'ACT-1006-1',
        type: 'created',
        author: 'Frank Zhou',
        content: 'Ticket created.',
        createdAt: '2026-06-15T22:48:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1007',
    title: 'Printer cannot scan to shared folder',
    requesterName: 'Grace Park',
    requesterEmail: 'grace.park@example.com',
    category: 'hardware',
    priority: 'low',
    status: 'waiting',
    description:
      'The copier on the 2nd floor can print, but scanning to the shared folder reports that the path is unavailable.',
    createdAt: '2026-06-13T05:30:00.000Z',
    updatedAt: '2026-06-14T07:10:00.000Z',
    assignedTo: 'IT - Daniel',
    activities: [
      {
        id: 'ACT-1007-1',
        type: 'created',
        author: 'Grace Park',
        content: 'Ticket created.',
        createdAt: '2026-06-13T05:30:00.000Z',
      },
      {
        id: 'ACT-1007-1b',
        type: 'status_changed',
        author: 'IT - Daniel',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-13T06:15:00.000Z',
      },
      {
        id: 'ACT-1007-2',
        type: 'note',
        author: 'IT - Daniel',
        content:
          'Shared-folder permissions may have changed after the migration. Waiting for the file-server admin to confirm the new path.',
        createdAt: '2026-06-14T07:10:00.000Z',
      },
      {
        id: 'ACT-1007-3',
        type: 'status_changed',
        author: 'IT - Daniel',
        content: 'Status changed from In Progress to Waiting.',
        createdAt: '2026-06-14T07:10:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1008',
    title: 'Emails wrongly flagged as spam',
    requesterName: 'Henry Adams',
    requesterEmail: 'henry.adams@example.com',
    category: 'email',
    priority: 'medium',
    status: 'resolved',
    description:
      'Emails from a client always land in the junk folder. I have already missed two important ones and would like the sender whitelisted.',
    createdAt: '2026-06-11T08:00:00.000Z',
    updatedAt: '2026-06-12T03:45:00.000Z',
    assignedTo: 'IT - Emma',
    activities: [
      {
        id: 'ACT-1008-1',
        type: 'created',
        author: 'Henry Adams',
        content: 'Ticket created.',
        createdAt: '2026-06-11T08:00:00.000Z',
      },
      {
        id: 'ACT-1008-1b',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-11T09:30:00.000Z',
      },
      {
        id: 'ACT-1008-2',
        type: 'reply',
        author: 'IT - Emma',
        content:
          'Added the client domain to the mail gateway allowlist and adjusted the anti-spam rules. Please keep an eye on it for a day or two.',
        createdAt: '2026-06-12T03:40:00.000Z',
      },
      {
        id: 'ACT-1008-3',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from In Progress to Resolved.',
        createdAt: '2026-06-12T03:45:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1009',
    title: 'New-hire computer setup',
    requesterName: 'Ivy Nguyen',
    requesterEmail: 'ivy.nguyen@example.com',
    category: 'other',
    priority: 'medium',
    status: 'open',
    description:
      'Three new colleagues start next Monday. We need to prepare laptops, email accounts, and basic software ahead of time.',
    createdAt: '2026-06-15T09:15:00.000Z',
    updatedAt: '2026-06-15T09:15:00.000Z',
    activities: [
      {
        id: 'ACT-1009-1',
        type: 'created',
        author: 'Ivy Nguyen',
        content: 'Ticket created.',
        createdAt: '2026-06-15T09:15:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1010',
    title: 'Shared-drive file locked and uneditable',
    requesterName: 'Jack Wilson',
    requesterEmail: 'jack.wilson@example.com',
    category: 'access',
    priority: 'high',
    status: 'in_progress',
    description:
      'The quarterly report on the finance shared drive shows as locked by another user, but colleagues say no one is using it, and it cannot be edited.',
    createdAt: '2026-06-16T02:50:00.000Z',
    updatedAt: '2026-06-16T03:30:00.000Z',
    assignedTo: 'IT - Emma',
    activities: [
      {
        id: 'ACT-1010-1',
        type: 'created',
        author: 'Jack Wilson',
        content: 'Ticket created.',
        createdAt: '2026-06-16T02:50:00.000Z',
      },
      {
        id: 'ACT-1010-2',
        type: 'status_changed',
        author: 'IT - Emma',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-16T03:00:00.000Z',
      },
      {
        id: 'ACT-1010-3',
        type: 'note',
        author: 'IT - Emma',
        content:
          'Located a leftover lock session on the file server and safely releasing it; should be editable within about 30 minutes.',
        createdAt: '2026-06-16T03:30:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1011',
    title: 'Outlook is slow and mailbox is full',
    requesterName: 'Karen Brooks',
    requesterEmail: 'karen.brooks@example.com',
    category: 'email',
    priority: 'medium',
    status: 'in_progress',
    description:
      'Outlook has become very slow and shows a warning that the mailbox is full. The .ost data file looks huge and I keep getting "cannot expand the folder" errors.',
    createdAt: '2026-06-16T04:00:00.000Z',
    updatedAt: '2026-06-16T04:20:00.000Z',
    assignedTo: 'Kyle',
    activities: [
      {
        id: 'ACT-1011-1',
        type: 'created',
        author: 'Karen Brooks',
        content: 'Ticket created.',
        createdAt: '2026-06-16T04:00:00.000Z',
      },
      {
        id: 'ACT-1011-2',
        type: 'status_changed',
        author: 'Kyle',
        content: 'Status changed from Open to In Progress.',
        createdAt: '2026-06-16T04:20:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1012',
    title: 'Outlook classic not syncing new mail',
    requesterName: 'Leo Schmidt',
    requesterEmail: 'leo.schmidt@example.com',
    category: 'email',
    priority: 'high',
    status: 'open',
    description:
      'Outlook classic stopped pulling in new mail since this morning. It is not syncing, a manual Send/Receive does nothing, and the status bar shows Working Offline.',
    createdAt: '2026-06-16T05:10:00.000Z',
    updatedAt: '2026-06-16T05:10:00.000Z',
    activities: [
      {
        id: 'ACT-1012-1',
        type: 'created',
        author: 'Leo Schmidt',
        content: 'Ticket created.',
        createdAt: '2026-06-16T05:10:00.000Z',
      },
    ],
  },
  {
    id: 'TKT-1013',
    title: 'Request delegate access to shared mailbox',
    requesterName: 'Mia Torres',
    requesterEmail: 'mia.torres@example.com',
    category: 'access',
    priority: 'medium',
    status: 'open',
    description:
      'I need delegate access to the shared mailbox support@example.com so I can cover tickets while a colleague is on leave.',
    createdAt: '2026-06-15T11:00:00.000Z',
    updatedAt: '2026-06-15T11:00:00.000Z',
    activities: [
      {
        id: 'ACT-1013-1',
        type: 'created',
        author: 'Mia Torres',
        content: 'Ticket created.',
        createdAt: '2026-06-15T11:00:00.000Z',
      },
    ],
  },
];
