-- Seed data generated from src/lib/mock-tickets.ts
-- Paste into the Supabase SQL Editor AFTER running schema.sql.

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1001', 'Cannot log in to company email', 'Alice Chen', 'alice.chen@example.com', 'email', 'high', 'open', 'Since this morning Outlook keeps saying my password is wrong, and webmail will not let me in either, but I am sure I did not change it. Please help as soon as possible.', null, '2026-06-16T01:12:00.000Z', '2026-06-16T01:12:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1001', 'created', 'Alice Chen', 'Ticket created.', '2026-06-16T01:12:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1002', 'Conference room Wi-Fi keeps dropping', 'Bob Martinez', 'bob.martinez@example.com', 'network', 'medium', 'in_progress', 'The Wi-Fi in the east-side conference room on the 3rd floor drops every few minutes and constantly interrupts video calls. Other floors are fine.', 'IT - Daniel', '2026-06-15T07:40:00.000Z', '2026-06-16T02:05:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1002', 'created', 'Bob Martinez', 'Ticket created.', '2026-06-15T07:40:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1002', 'status_changed', 'IT - Daniel', 'Status changed from Open to In Progress.', '2026-06-15T08:15:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1002', 'note', 'IT - Daniel', 'Contacted the network vendor. Initial guess is AP overload in that area; scheduling an on-site check.', '2026-06-16T02:05:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1003', 'Request to install Adobe Photoshop', 'Carol Wang', 'carol.wang@example.com', 'software', 'low', 'waiting', 'Marketing needs Photoshop to work on event assets. Requesting installation on my work computer and a license assignment.', 'IT - Emma', '2026-06-14T03:20:00.000Z', '2026-06-15T06:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1003', 'created', 'Carol Wang', 'Ticket created.', '2026-06-14T03:20:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1003', 'reply', 'IT - Emma', 'This needs the department manager to approve the license budget. Sent a confirmation email and waiting for a reply.', '2026-06-15T06:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1003', 'status_changed', 'IT - Emma', 'Status changed from Open to Waiting.', '2026-06-15T06:30:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1004', 'Laptop will not power on', 'David Kim', 'david.kim@example.com', 'hardware', 'urgent', 'in_progress', 'Pressing the power button does nothing, no indicator light, and I have already swapped the charger. I have a client demo tomorrow and need this fixed urgently.', 'IT - Daniel', '2026-06-16T00:05:00.000Z', '2026-06-16T03:10:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1004', 'created', 'David Kim', 'Ticket created.', '2026-06-16T00:05:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1004', 'status_changed', 'IT - Daniel', 'Status changed from Open to In Progress.', '2026-06-16T00:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1004', 'note', 'IT - Daniel', 'Prepared a loaner laptop and migrating data; also contacting the vendor to test the mainboard.', '2026-06-16T03:10:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1005', 'Need GitHub organization access', 'Eva Liu', 'eva.liu@example.com', 'access', 'medium', 'resolved', 'New engineer onboarding. I need to join the company GitHub organization and get write access to the backend repository.', 'IT - Emma', '2026-06-12T02:00:00.000Z', '2026-06-13T01:25:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1005', 'created', 'Eva Liu', 'Ticket created.', '2026-06-12T02:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1005', 'status_changed', 'IT - Emma', 'Status changed from Open to In Progress.', '2026-06-12T06:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1005', 'reply', 'IT - Emma', 'Sent the org invite and added you to the backend team with write access. Please check your email and accept the invite.', '2026-06-13T01:20:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1005', 'status_changed', 'IT - Emma', 'Status changed from In Progress to Resolved.', '2026-06-13T01:25:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1006', 'VPN connection times out', 'Frank Zhou', 'frank.zhou@example.com', 'network', 'high', 'open', 'Working remotely from home. Connecting to the company VPN keeps timing out, which blocks access to internal systems.', null, '2026-06-15T22:48:00.000Z', '2026-06-15T22:48:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1006', 'created', 'Frank Zhou', 'Ticket created.', '2026-06-15T22:48:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1007', 'Printer cannot scan to shared folder', 'Grace Park', 'grace.park@example.com', 'hardware', 'low', 'waiting', 'The copier on the 2nd floor can print, but scanning to the shared folder reports that the path is unavailable.', 'IT - Daniel', '2026-06-13T05:30:00.000Z', '2026-06-14T07:10:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1007', 'created', 'Grace Park', 'Ticket created.', '2026-06-13T05:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1007', 'status_changed', 'IT - Daniel', 'Status changed from Open to In Progress.', '2026-06-13T06:15:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1007', 'note', 'IT - Daniel', 'Shared-folder permissions may have changed after the migration. Waiting for the file-server admin to confirm the new path.', '2026-06-14T07:10:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1007', 'status_changed', 'IT - Daniel', 'Status changed from In Progress to Waiting.', '2026-06-14T07:10:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1008', 'Emails wrongly flagged as spam', 'Henry Adams', 'henry.adams@example.com', 'email', 'medium', 'resolved', 'Emails from a client always land in the junk folder. I have already missed two important ones and would like the sender whitelisted.', 'IT - Emma', '2026-06-11T08:00:00.000Z', '2026-06-12T03:45:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1008', 'created', 'Henry Adams', 'Ticket created.', '2026-06-11T08:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1008', 'status_changed', 'IT - Emma', 'Status changed from Open to In Progress.', '2026-06-11T09:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1008', 'reply', 'IT - Emma', 'Added the client domain to the mail gateway allowlist and adjusted the anti-spam rules. Please keep an eye on it for a day or two.', '2026-06-12T03:40:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1008', 'status_changed', 'IT - Emma', 'Status changed from In Progress to Resolved.', '2026-06-12T03:45:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1009', 'New-hire computer setup', 'Ivy Nguyen', 'ivy.nguyen@example.com', 'other', 'medium', 'open', 'Three new colleagues start next Monday. We need to prepare laptops, email accounts, and basic software ahead of time.', null, '2026-06-15T09:15:00.000Z', '2026-06-15T09:15:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1009', 'created', 'Ivy Nguyen', 'Ticket created.', '2026-06-15T09:15:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1010', 'Shared-drive file locked and uneditable', 'Jack Wilson', 'jack.wilson@example.com', 'access', 'high', 'in_progress', 'The quarterly report on the finance shared drive shows as locked by another user, but colleagues say no one is using it, and it cannot be edited.', 'IT - Emma', '2026-06-16T02:50:00.000Z', '2026-06-16T03:30:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1010', 'created', 'Jack Wilson', 'Ticket created.', '2026-06-16T02:50:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1010', 'status_changed', 'IT - Emma', 'Status changed from Open to In Progress.', '2026-06-16T03:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1010', 'note', 'IT - Emma', 'Located a leftover lock session on the file server and safely releasing it; should be editable within about 30 minutes.', '2026-06-16T03:30:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1011', 'Outlook is slow and mailbox is full', 'Karen Brooks', 'karen.brooks@example.com', 'email', 'medium', 'in_progress', 'Outlook has become very slow and shows a warning that the mailbox is full. The .ost data file looks huge and I keep getting "cannot expand the folder" errors.', 'Kyle', '2026-06-16T04:00:00.000Z', '2026-06-16T04:20:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1011', 'created', 'Karen Brooks', 'Ticket created.', '2026-06-16T04:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1011', 'status_changed', 'Kyle', 'Status changed from Open to In Progress.', '2026-06-16T04:20:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1012', 'Outlook classic not syncing new mail', 'Leo Schmidt', 'leo.schmidt@example.com', 'email', 'high', 'open', 'Outlook classic stopped pulling in new mail since this morning. It is not syncing, a manual Send/Receive does nothing, and the status bar shows Working Offline.', null, '2026-06-16T05:10:00.000Z', '2026-06-16T05:10:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1012', 'created', 'Leo Schmidt', 'Ticket created.', '2026-06-16T05:10:00.000Z');

insert into tickets (id, title, requester_name, requester_email, category, priority, status, description, assigned_to, created_at, updated_at) values ('TKT-1013', 'Request delegate access to shared mailbox', 'Mia Torres', 'mia.torres@example.com', 'access', 'medium', 'open', 'I need delegate access to the shared mailbox support@example.com so I can cover tickets while a colleague is on leave.', null, '2026-06-15T11:00:00.000Z', '2026-06-15T11:00:00.000Z');
insert into activities (ticket_id, type, author, content, created_at) values ('TKT-1013', 'created', 'Mia Torres', 'Ticket created.', '2026-06-15T11:00:00.000Z');

